apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: revalenz-backend
spec:
  template:
    spec:
      containers:
        - image: gcr.io/${PROJECT_ID}/revalenz-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      timeoutSeconds: 300
      containerConcurrency: 80
      volumes:
        - name: cloudsql
          cloudSqlInstance: ${PROJECT_ID}:${REGION}:${INSTANCE_NAME} 